### ISSUE TITLE
plugin-installation-manager add '-plugin' suffix to my plugins files

### ISSUE THREAD

**Issue by eyonasi** [jenkinsci/plugin-installation-manager-tool#100]
Hi,
I am trying to install plugins from a plugins txt file and it adds '-plugin' suffix for every plugin and as a result it does not appear in the jenkins update center.
e.g:

Downloading plugin conditional-buildstep-plugin from url: https://updates.jenkins.io/download/plugins/conditional-buildstep-plugin/1.3.6/conditional-buildstep-plugin.hpi

while in plugins.txt file:
conditional-buildstep:1.3.6

Command:
java -jar plugin-management-cli/target/jenkins-plugin-manager-1.0.3-SNAPSHOT.jar --war ../jenkins.war --plugin-file ../plugins.txt

**Comment by timja** [comment]
PR here: https://github.com/jenkinsci/plugin-installation-manager-tool/pull/94

**Comment by eyonasi** [comment]
Thanks! closing this then.

**Comment by eyonasi** [comment]
There is a PR already in progress.

**Comment by timja** [comment]
Cool, did you try out the PR and it worked for you?

**Comment by eyonasi** [comment]
Now I've tried it out, seems it is acting the same way.

Downloading plugin blueocean-core-js-plugin from url:
https://updates.jenkins.io/download/plugins/blueocean-core-js-plugin/1.11.1/blueocean-core-js-plugin.hpi

**Comment by timja** [comment]
could you give the command link you used and make sure you ran `mvn clean` in between? or download it from here:

https://repo.jenkins-ci.org/incrementals/io/jenkins/plugin-management/plugin-management-cli/1.0.3-rc348.b9ddbcdd9713/plugin-management-cli-1.0.3-rc348.b9ddbcdd9713.jar

**Comment by eyonasi** [comment]
I forgot about maven clean.
Now verified i am not hitting it.
