### ISSUE TITLE
Update tests to use the SystemOutRule rule

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/plugin-installation-manager-tool#103]
Currently several tests redirect the STDOUT to verify the output. In such case the tool's output does not get displayed in the execution log. Instead of that, it would be better to use a special JUnit Rule which can capture the output.

See the example in https://github.com/jenkinsci/plugin-installation-manager-tool/pull/102

```
    @Rule
    public final SystemOutRule systemOutRule = new SystemOutRule().enableLog();
```

```
    assertThat(systemOutRule.getLog(), not(containsString("uithemes")));
```

**Comment by stefanbirkner** [comment]
This should be fixed by #123.
