### ISSUE TITLE
Build update center tree structure?

### ISSUE THREAD

**Issue by ricksbrown** [jenkinsci/plugin-installation-manager-tool#109]
Below I describe a use case for plugin-installation-manager-tool that is not currently catered for. I was going to just do it but it would be a non-trivial amount of work so I thought I'd float it first. In the meantime we are going to have to continue using custom scripts to augment plugin-installation-manager-tool.

There are actually two different consumers for the downloaded plugins:

* Jenkins (obviously)
* (On-prem) Jenkins Update Center (UC)

Jenkins requires the plugins to be downloaded into a flat directory structure, that's what plugin-installation-manager-tool does. Job done.

Since our Jenkins is not allowed to connect to the cloud we must also take the plugins and upload them to an on-premises server, it's not a true Update Center, but we upload them in the same format:

`host.example.com/updates.jenkins.io/download/plugins/{plugin-name}/{plugin-version}/{plugin-name}.hpi`

We have a script that downloads them into the correct directory structure, which is basically a very selective mirror of the Jenkins Update Center, just the plugins we need.

I was thinking plugin-installation-manager-tool could potentially do this too, either with a different mode OR it might make sense to build this tree structure in the cache directory. That way plugins would only ever be downloaded once, multiple runs of the script would potentially be much faster, only downloading plugins they had not seen before.

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/juseppe and https://github.com/jenkins-infra/update-center2 can already generate update center structures based on various inputs. I do not think it makes sense to reimplement such functionality in this tool as well, it would be better to just unify configuration file format, e.g. by supporting a https://github.com/jenkinsci/jep/blob/master/jep/309/README.adoc specification or another format

**Comment by timja** [comment]
I don't think this belongs here in the tool, it's for plugins updates not update center generation
