### ISSUE TITLE
Available updates updates past max supported version

### ISSUE THREAD

**Issue by timja** [jenkinsci/plugin-installation-manager-tool#169]
workflow-durable-task-step:2.35

with the current LTS 2.235.5 gets upgraded to 2.36 which requires 2.248

**Comment by timja** [comment]
So I can't reproduce this anymore.

I tried with both 2.235 and durable-task-step and 2.249 and branch-api

Both of them behave correctly.

I've also checked the code and it uses a version specific update center which should only return updates if they are supported for that core version.

https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/Main.java#L45

The only thing I can think of is the dynamic tier wasn't generated yet for that LTS line? or something weird in update center generation?

@gregswift I saw you commented on the other issue about this have you hit it recently?

@daniel-beck am I missing something?

We could consult the `plugin-versions.json` file too but I thought the version specific update center would be enough

**Comment by timja** [comment]
ah found it, it's using the plugin info json inside of a method call instead of the version specific update center, looks like a bug I'll see if there's a reason that was done or just a typo

**Comment by daniel-beck** [comment]
Investigation hint for the future:

```
$ curl --location --silent --fail https://updates.jenkins.io/update-center.actual.json?version=2.235.5 | jq --raw-output '.plugins["workflow-durable-task-step"].version'
2.35

**Comment by timja** [comment]
Tests need some re-work to fix this, will come back to it

**Comment by timja** [comment]
https://github.com/jenkinsci/plugin-installation-manager-tool/pull/220
