### ISSUE TITLE
plugin.txt format differs

### ISSUE THREAD

**Issue by halkeye** [jenkinsci/plugin-installation-manager-tool#183]
install-plugins.sh takes the custom url as 4th parameter

https://github.com/jenkinsci/docker/blob/37a170fbb09fb50a63612551ca1d16f7752013bb/install-plugins.sh#L41-L44

But https://github.com/jenkinsci/plugin-installation-manager-tool/blob/d6be728366067188042b7e80a875c62ef7aeb2b8/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/util/PluginListParser.java#L149-L155 ignores the lockfile parameter

so my existing plugins.txt with
`html5-notifier:custom::https://files.halkeye.net/html5-notifier-plugin.hpi` does not function

Is this intentional (should I update my plugins.txt) or accidental (bug and needs a PR)

**Comment by timja** [comment]
Somewhat intentional I think so that you don’t need to have an empty :.

Ideally update your file, but a PR with a test that makes both versions work would be accepted.

**Comment by halkeye** [comment]
the downside is of course is that its not a drop in replacement for the existing script

I'll see what i can do.
