### ISSUE TITLE
Not able to download plugins through private repo

### ISSUE THREAD

**Issue by oganga** [jenkinsci/plugin-installation-manager-tool#191]
Hi 

Trying to use the tool behind company firewall by using Artifactory as a proxy.
Have been able to download update json files by using JENKINS_PLUGIN_INFO, JENKINS_INCREMENTALS_REPO_MIRROR, JENKINS_UC_EXPERIMENTAL, JENKINS_UC environment variables.

But for the actual download of the plugins it is always trying wrong url. Either trying the direkte url to the Jenkins update center or wrong path pointing at company Artifactory.

If it is a bug or missing feature, not sure.

Maybe use something like JENKINS_UC_DOWNLOAD environment variable or add a new command line flag to enable download plugins from company artifact proxy.

**Comment by timja** [comment]
the updates file say where to download the plugins from.
if you don't want them to be downloaded from there you need to provides your owns updates.json file.

**Comment by oganga** [comment]
So I need to maintain a updates.json by hand with all plugins and their dependencies?

This have not been the case earlier with https://github.com/jenkinsci/docker/blob/master/install-plugins.sh(which also appear to be broken now: https://github.com/jenkinsci/docker/commit/d1d51c8da7032604acf56e4abed4afb31bd813a2)  was hoping to be able to use the plugin-manager tool instead off

**Comment by timja** [comment]
It might have been hacked in before, but the current ways are either:

1. allow your proxy to be able to contact our mirrors 
2. run your own update center https://github.com/jenkinsci/juseppe, https://github.com/jenkins-infra/update-center2

a couple of options

cc @daniel-beck who is more familiar with this area

**Comment by oganga** [comment]
Hi 

We are actually doing a bit of both; running out own update center with JFrog Artifactory, which is allowed by company firewall to talk to the internet.

I will try and create a PR with a possible fix later this week.

**Comment by raspy** [comment]
Verified it works with version 2.1.0.

**Comment by oganga** [comment]
Thanks for testing.
