### ISSUE TITLE
Move Plugin Installation Manager issues from Jenkins Jira to GitHub Issues

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/plugin-installation-manager-tool#202]
When the project started, it was using Jenkins Jira instead of GitHub Issues. Many issues are still open here: https://issues.jenkins-ci.org/issues/?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20plugin-installation-manager-tool%20 . It would be great to scrub the issues and to move relevant ones to GitHub Issues

**Comment by hp77-creator** [comment]
Hey, I went through the JIRA issues, I can scrub those from there and raise those here but I wouldn't be able to work out which will be valid, so It will be better if you or someone review them and close the ones that aren't needed. Is this okay? Bringing those issues will help to keep track of which are enhancements or bugs and which should be incorporated in the plugin tool enhancement project.

**Comment by timja** [comment]
Thanks @hp77-creator!
