### ISSUE TITLE
"Available updates" shows updates if 'latest' is used

### ISSUE THREAD

**Issue by reinholdfuereder** [jenkinsci/plugin-installation-manager-tool#208]
`jenkins-plugin-cli --available-updates -f plugins.txt`
... shows IMHO all plugins, including those that are definitely already on latest version (i.e. up-to-date):

```
Available updates:
ace-editor (latest) has an available update: 1.1
analysis-model-api (latest) has an available update: 9.1.0
antisamy-markup-formatter (latest) has an available update: 2.1
blueocean-autofavorite (latest) has an available update: 1.2.4
blueocean-display-url (latest) has an available update: 2.4.0
blueocean (latest) has an available update: 1.24.1
bouncycastle-api (latest) has an available update: 2.18
branch-api (latest) has an available update: 2.6.0
...
```

E.g. "Branch API v2.6.0" is (already) installed (in this version and is the latest available version) => Should not be shown for option "--available-updates" (I had hoped/expected)!?

**Comment by Larusso** [comment]
I think the expectation is that this command returns a complete new `txt`/`yml` file with all your plugins. Could mean it returns the same file back.

**Comment by timja** [comment]
the difference here is that latest isn't being considered as a (pseudo) version and it's giving a new version when really latest should just be ignored in the version update check.

**Comment by reinholdfuereder** [comment]
> I think the expectation is that this command returns a complete new `txt`/`yml` file with all your plugins. Could mean it returns the same file back.

@Larusso Please correct me if I misunderstand you: But do you really expect that funtionality from an "`--available-updates`" option?

Maybe it could make sense to add another option, maybe named "`--list-with-available-updates`", that does what you are describing, i.e. generating a new list with all your plugins with latest available versions, which could return the same file back (if there are no updates available at all).

This would also nicely match the 7h ago mentioned new idea/approach of @timja in #173 (https://github.com/jenkinsci/plugin-installation-manager-tool/issues/173#issuecomment-727257674) with respect to fixing "`--list`", wouldn't it?

**Comment by timja** [comment]
If you specify an output format it already does that (yaml or txt).

The console one is for humans although not really sure why you would want to use it

**Comment by reinholdfuereder** [comment]
@timja First of all thanks for the fix!

Secondly, I am not sure that I understand your comment https://github.com/jenkinsci/plugin-installation-manager-tool/issues/208#issuecomment-727528118 correctly: Does that mean if I specify "only" the option "`--output {json,stdout,yaml}`" (no, in addition to certain other flags!? Which?) then this will return all plugins (including latest versions) AND available updates?

**Comment by timja** [comment]
So available updates will return you a complete plugins file including any updates if you specify and output format of yaml or txt.

If you don’t specify an output format it uses a console reporter which only outputs plugins with an update
