### ISSUE TITLE
Jenkins plugin manager rejects plugins.txt.override file

### ISSUE THREAD

**Issue by jansohn** [jenkinsci/plugin-installation-manager-tool#209]
We switched from `install-plugins.sh` to `jenkins-plugin-manager` in our Dockerfile and noticed that it doesn't support specifying the `plugins.txt.override` file as a parameter.

    $ java -jar /usr/lib/jenkins-plugin-manager.jar -f /usr/share/jenkins/ref/plugins.txt.override
    Unknown file type, file must have .yaml/.yml or .txt extension

We worked around the issue like this for the time being:

    $ java -jar /usr/lib/jenkins-plugin-manager.jar -p $(< /usr/share/jenkins/ref/plugins.txt.override)

I think it would still make sense to allow `.override` files in this case...

**Comment by timja** [comment]
it's just the file extension, rename it to `plugins.override.txt`

**Comment by jansohn** [comment]
> it's just the file extension, rename it to `plugins.override.txt`

It needs to end with `.override` otherwise it won't override when starting the docker container (see https://github.com/jenkinsci/docker/#plugin-installation-manager-cli-preview-2). Please re-open...

**Comment by timja** [comment]
`.override` is only for config files not installing plugins

**Comment by jetersen** [comment]
This paragraph is misplaced under https://github.com/jenkinsci/docker/#plugin-installation-manager-cli-preview
> In case you do want to override, append '.override' to the name of the reference file. E.g. a file named /usr/share/jenkins/ref/config.xml.override will overwrite an existing config.xml file in JENKINS_HOME.

**Comment by jansohn** [comment]
> 
> 
> `.override` is only for config files not installing plugins

OK, seems like I've been using it wrong all along then...
