### ISSUE TITLE
Unable to download plugin

### ISSUE THREAD

**Issue by ldormoy** [jenkinsci/plugin-installation-manager-tool#218]
Hello,

I'm running a dockerized Jenkins using the official image and installing my plugins this way:

```
jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
```

It's been more than 12 hours than my builds (running on GitHub Actions) systematically fail to download all the plugins mentioned in the `plugins.txt` file. The error is always:

```
Unable to download [PLUGIN_NAME]
```

It is always a different plugin.

I tried with HTTPS and HTTP, with updates.jenkins.io and with a direct mirror address, it never worked.

Is there any way I can circomvent this issue?

**Comment by ldormoy** [comment]
Just found a corresponding ticket in the Jenkins JIRA: https://issues.jenkins.io/projects/INFRA/issues/INFRA-2808

**Comment by timja** [comment]
the site was basically completely down (it's somewhat up now), the tool already retries and more people hitting it won't make it come back faster.

**Comment by ldormoy** [comment]
Okay, thanks for the confirmation @timja , gonna close this issue then.
