### ISSUE TITLE
Support to use the latest compatible version for a given plugin and jenkins core

### ISSUE THREAD

**Issue by v1v** [jenkinsci/plugin-installation-manager-tool#219]
Not sure if this is a valid requirement but I'd say https://github.com/jenkinsci/plugin-installation-manager-tool/pull/65 is a good way to prevent any issues when upgrading a plugin that requires a bump for the jenkins core.

I'd consider another use case when using latest should install the latest supported version for the given core. I don't know if that's something that was discarded in the past.

For instance:

Let's say, given the `2.252` core version and `workflow-basic-steps` as of today:

- the latest version for workflow-basic-steps is `2.23` but it requires `2.263`
```
$ curl -s https://updates.jenkins.io/current/update-center.actual.json | jq '.plugins["workflow-basic-steps"].version'
"2.23"
$ curl -s https://updates.jenkins.io/current/update-center.actual.json | jq '.plugins["workflow-basic-steps"].requiredCore'
"2.263"
```

Therefore when doing `jenkins-plugin-cli --plugins workflow-basic-steps` there is an error

```
io.jenkins.tools.pluginmanager.impl.VersionCompatibilityException: 
workflow-basic-steps (2.23) requires a greater version of Jenkins (2.263) than 2.252 in /usr/share/jenkins/jenkins.war
	at io.jenkins.tools.pluginmanager.impl.PluginManager.checkVersionCompatibility(PluginManager.java:430)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:153)
	at io.jenkins.tools.pluginmanager.impl.PluginManager.start(PluginManager.java:112)
	at io.jenkins.tools.pluginmanager.cli.Main.main(Main.java:63)

workflow-basic-steps (2.23) requires a greater version of Jenkins (2.263) than 2.252 in /usr/share/jenkins/jenkins.war
```

As far as I see the file `plugin-versions.json` contains all the versions and required core version too:

```
$ curl -s https://updates.jenkins.io/current/plugin-versions.json | jq -r '.plugins["workflow-basic-steps"]["2.23"].requiredCore'   
2.263
$ curl -s https://updates.jenkins.io/current/plugin-versions.json | jq -r '.plugins["workflow-basic-steps"]["2.22"].requiredCore' 
2.249.1
```

What I'd expect is given `workflow-basic-steps:latest` and jenkins-core 2.252 the upgrade should be done to `2.22` which it's the latest supported version for that particular core.

Is there any specific flag that can help me to accomplish that particular requirement? Or at leats, to avoid the upgrade of `workflow-basic-steps:latest` and move forward to the next plugins?

I've been using some combinations of flags but I cannot find if there is one for such.

Thanks

**Comment by timja** [comment]
similar to https://github.com/jenkinsci/plugin-installation-manager-tool/issues/169

**Comment by timja** [comment]
Hmm this already seems to work?

```
wget https://get.jenkins.io/war/2.252/jenkins.war
java -jar plugin-management-cli/target/jenkins-plugin-manager-*.jar --plugins workflow-basic-steps  --war jenkins.war -d plugins
```

> Downloading plugin workflow-basic-steps from url: https://updates.jenkins.io/download/plugins/workflow-basic-steps/2.22/workflow-basic-steps.hpi

Basically we use what's called an update site tier (which includes your core version):

```
curl --location --silent --fail https://updates.jenkins.io/update-center.actual.json?version=2.252 | jq --raw-output '.plugins["workflow-basic-steps"].version'
2.22
```

See more in the update center docs:
https://updates.jenkins.io/#version-specific-update-sites
and
https://github.com/jenkins-infra/update-center2/tree/master/site#dynamic-update-site-tiers

Is this exactly the issue that you hit, or theoretical in some way?

@daniel-beck in case I missed something

**Comment by daniel-beck** [comment]
Tiered update sites are used to provide plugin releases compatible with the user-specified core version; there is no reason for anyone to ever access the `current/` update site in an installation/deployment scenario. The correct URL for that is always `/update-center[.actual].json?version=2.xxx[.y]`.

Besides that, I don't know enough about how this component works to contribute to this conversation.

**Comment by timja** [comment]
the component doesn't `current` it uses the tiered update sites.

**Comment by v1v** [comment]
Aha! I see now, thanks for the clarification since I used the `current/` update site from one of the mirrors, and it works now by using the default setup:

Although if I use `http://mirror.xmission.com/jenkins/updates/update-center.json` the issue still persists, so maybe there is something wrong with that particular mirror, while if I use `http://mirror.xmission.com/jenkins/updates/stable/update-center.actual.json`it works.

Other than that, thanks again and sorry for the false alarm.

**Comment by timja** [comment]
you should just always use the update site directly (https://updates.jenkins.io)
We don't direct update site json files to mirrors at all, (even though the mirror's do have the files)
