### ISSUE TITLE
Add support for generating a new plugin file based on current Jenkins folder

### ISSUE THREAD

**Issue by timja** [jenkinsci/plugin-installation-manager-tool#227]
Ideally it should support the following outputs:

* console (human readable)
* txt
* yaml

The `--list` flag along with the `--output` flags can probably be used for this

Also relevant https://github.com/jenkinsci/plugin-installation-manager-tool/pull/226 and https://github.com/jenkinsci/plugin-installation-manager-tool/issues/173

**Comment by MarkEWaite** [comment]
> It should be great to generate the plugin.txt out of the jenkins, so that this tool could be used easily to copy plugins from instance to another instance...

The Jenkins [groovy script console](https://www.jenkins.io/doc/book/managing/script-console/) can generate the contents of a `plugins.txt` file with the script:

```
Jenkins.instance.pluginManager.plugins
    .collect()
    .sort { it.getShortName() }
    .each {
        plugin -> println("${plugin.getShortName()}:${plugin.getVersion()}")
    }
return
```

**Comment by pamgluss-slack** [comment]
I am confused, what does --output txt / --output yaml actually do right now? Isn't this their intended purpose?

**Comment by MarkEWaite** [comment]
> I am confused, what does --output txt / --output yaml actually do right now? Isn't this their intended purpose?

I use the following command to generate a plugins.txt file based on the existing plugins.txt file and available updates.

```
$ ./jenkins-plugin-cli.sh --jenkins-version 2.319.3 --plugin-download-directory ref/plugins --plugin-file plugins.txt --no-download --available-updates --output txt > x && mv x plugins.txt
```

In my case, it needs the "starter" plugins.txt file.  It doesn't generate a fresh one from the `ref/plugins` directory.
