### ISSUE TITLE
Add support for Basic HTTP authentication

### ISSUE THREAD

**Issue by scurvydoggo** [jenkinsci/plugin-installation-manager-tool#245]
We have developed some in-house Jenkins plugins to suit some specific use cases in our company, which aren't really general purpose enough to merit the update center (i.e we rely on some local implementation details to speed development and avoid generalising the problem too much).

As such the plugins are hosted on our Artifactory service which requires authorisation to access.

As the `install-plugins.sh` script used `curl` under the hood, we were able to auth via a `.netrc` file. Unfortunately we aren't able to migrate to this tool as I don't think it supports any auth mechanism.

**Comment by jetersen** [comment]
Are you also using antifactory as a mirror, so we could apply authentication as a whole, or is it only for some of your own plugins you need to apply authentication for?

**Comment by jetersen** [comment]
Sometimes the simplest solution in my opinion is such cases is a reverse proxy that handles the authentication, so the application does not know about it.

**Comment by scurvydoggo** [comment]
Thanks for the suggestion, the reverse proxy will be a good workaround until the feature is added.

**Comment by kwin** [comment]
I think it makes sense to allow to configure basic authentication credentials for certain URLs via dedicated CLI options and then configure those correctly in https://github.com/jenkinsci/plugin-installation-manager-tool/blob/e01e3c49269a80bfa1ce2f6038d101fee8d325df/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1139 via the means outlined at https://hc.apache.org/httpcomponents-client-4.5.x/current/tutorial/html/authentication.html.
