### ISSUE TITLE
Use latest compatible version of plugins when generating YAML file

### ISSUE THREAD

**Issue by nre-ableton** [jenkinsci/plugin-installation-manager-tool#257]
Given that the tool requires a Jenkins JAR, it would be nice if it only considered the latest compatible version of plugins when generating the `plugins.yaml` file. I routinely run into this issue, for example most recently after having updated Jenkins to 2.263.2, and then noticing that the tool had upgraded `branch-api` to an incompatible version.

We update plugins by running this command:

```
java -jar <path to tool JAR file> \
          --available-updates \
          --output YAML \
          --plugin-file /tmp/plugins.yaml \
          --war <path to Jenkins WAR file> \
        > /tmp/updated-plugins.yaml
```

...and then we take the resulting `plugins.yaml` file, put it in source control, etc. When deploying Jenkins, we then run the following command:

```
    java -jar <path to tool JAR file> \
      --plugin-download-directory /opt/jenkins/home/plugins \
      --plugin-file <path to plugins.yaml> \
      --war <path to Jenkins WAR file> \
      --latest false \
      --verbose
```

We only learn about the incompatibility when running the second deployment step, where we get an error message like `branch-api (2.6.3) requires a greater version of Jenkins (2.264) than 2.263.2 in /opt/jenkins/lib/jenkins-2.263.2.war`. In short, it would be really nice if the tool would generate a YAML file with the latest compatible version. I'm not sure if this is easy/possible, but given that the WAR file is being passed to the tool I would hope that it is.

**Comment by timja** [comment]
It should already do this as of https://github.com/jenkinsci/plugin-installation-manager-tool/issues/169

**Comment by nre-ableton** [comment]
Hmm, strange, we are using 2.5.0. I will investigate further though.

**Comment by nre-ableton** [comment]
This seems to have been a configuration error in our Ansible playbooks which used an outdated version of the tool. As of version 2.1.2, the feature does work correctly. Sorry for the noise!
