### ISSUE TITLE
[JENKINS-58229] Optionally skip plugins listed in plugins.txt on latest version

### ISSUE THREAD

**Issue by hp77-creator** [jenkinsci/plugin-installation-manager-tool#265]
Use case: updating all currently installed plugins to their latest version.

It’s hard to know if plugins are the latest version until checking the update center because to find out what version an installed plugin is, we parse the manifest, which doesn’t give any info about if that version is the latest. In general, information about plugins needs to be retrieved from the update center sooner - this will also help with displaying security warnings only relevant to the plugins in which the user is interested.

Related to: https://issues.jenkins-ci.org/browse/JENKINS-58191

Reporter: Natasha Stopa
#202

**Comment by MarkEWaite** [comment]
Resolved with #44
