### ISSUE TITLE
Plugin manager is losing plugins installed in previous images

### ISSUE THREAD

**Issue by gutschet** [jenkinsci/plugin-installation-manager-tool#276]
Hello,

We have a hierarchical structure auf our images:

- jenkins-base (`FROM jenkins:jenkins`) installs plugins needed by all our projects, specified in `plugins-base.txt`.
- jenkins-project-<projectID> (`FROM jenkins-base`) installs additional plugins specific to the project, specified in `plugins-project.txt`.

That works fine, when I use the old install-plugins.sh method. When I start a jenkins container from my jenkins-project-<projectID> image, I get a jenkins instance with the plugins fro both `plugins-base.txt` and `plugins-project.txt`. 

But when I use the new plugin-installation-manager-tool with the same plugin lists, the project specific image only has the plugins from `plugins-project.txt` (and their dependencies) but not the plugins from `plugins-base.txt`.

My installation commands:

- with install-plugins.sh script: `RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins-project.txt`
- with plugin-installation-manager-tool: `RUN java -Dhttps.proxyHost=${PROXY_HOST} -Dhttps.proxyPort=${PROXY_PORT} -jar /usr/lib/jenkins-plugin-manager.jar --verbose -f /usr/share/jenkins/ref/plugins-project.txt`

Is this a bug or am I using the new tool wrong?

Kind regards
Timo

**Comment by timja** [comment]
I think this doesn't happen on newer versions but the docker image it not up to date with our release, see https://github.com/jenkinsci/docker/pull/1071

**Comment by gutschet** [comment]
Ah great, thanks for the quick answer. I was wondering because i set up a jenkins instance for a new project and it crashed because the plugins from base image were not installed. So I guess I have to wait for jenkins to integrate the new version to the image.

Have a nice weekend

**Comment by oleg-nenashev** [comment]
Sorry for losing. Yes, you just need to wait. The recent weekly release should already include the change

**Comment by timja** [comment]
> Sorry for losing. Yes, you just need to wait. The recent weekly release should already include the change

from what I can tell it doesn't

**Comment by oleg-nenashev** [comment]
You are right @timja . https://github.com/jenkinsci/docker/pull/1071 was closed in favor of another PR, not merged. https://github.com/jenkinsci/docker/pull/1073 should land it

**Comment by MarkEWaite** [comment]
Based on the earlier comments that this is resolved in newer releases of the tool, I'm closing it.
