### ISSUE TITLE
Support connection pooling

### ISSUE THREAD

**Issue by kwin** [jenkinsci/plugin-installation-manager-tool#291]
Currently the HttpClient is not reused among multiple connections. Each time a plugin is downloaded a new client is created (with a new connection pool): https://github.com/jenkinsci/plugin-installation-manager-tool/blob/1de193570ae32ea0347614a912488a4f3fa4d2a9/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/impl/PluginManager.java#L1139.

Instead it makes sense to reuse the same HttpClient with the same underlying HttpConnectionPool for the whole lifetime of the `PluginManager`. I propose to make the `PluginManager` implement `Closeable` and create the HttpClient lazily and close it with the `close` method.

**Comment by timja** [comment]
Makes sense, PRs welcome.

Ideally with a medium size plugin set with a timing before and after to make sure there's no regression
