### ISSUE TITLE
Support other hash functions than sha256

### ISSUE THREAD

**Issue by kyounger** [jenkinsci/plugin-installation-manager-tool#299]
Due to legacy uses, sha1 is still used by some update centers. Until those are updated to use proper sha256/sha512 this tool breaks when used with them. It would be nice in the long run to parameterize this config.

**Comment by timja** [comment]
which update centers? 

Is it better to just update them?

**Comment by kyounger** [comment]
In my situation, I'm unable to affect the updates of those UCs. I am told it will be coming, but no there is currently not ETA. We are currently implementing and were needing to use the `--list` feature that @oleg-nenashev fixed, but when upgrading to the latest version, it broke use of sha1.

I completely agree that all UCs should be updated. In this situation, the UCs are behind properly secured HTTPS endpoints, so it's a bit less of a concern. I didn't elevate this option to a proper CliOption, as it buried this a bit for those that really needed it for legacy purposes, but I think there is still a large user base of commercial Jenkins users that require sha1 support for now.

**Comment by timja** [comment]
Is this an internal UC or is it open source somewhere?

**Comment by kyounger** [comment]
The CloudBees Update Centers still use sha1.
