### ISSUE TITLE
install plugins without restart

### ISSUE THREAD

**Issue by gopivalleru** [jenkinsci/plugin-installation-manager-tool#309]
### Dependencies

None

### Feature Request

If I'm installing any plugin from Jenkins UI then I can select to option to "install plugins without restart". Right now plugin installation manager tool has no option to install plugins without restart.

**Comment by timja** [comment]
@oleg-nenashev any thoughts on this?

**Comment by oleg-nenashev** [comment]
Plugin Installation Manager was designed as an standalone plugin management.

Indeed we could add a new mode which installs plugins on a running Jenkins instance using REST API or CLI, but I am not sure the tool is a best location for that. Maybe it makes sense to use Plugin Installation Manager as a library and add the functionality to Jenkins CLI directly

**Comment by hp77-creator** [comment]
@oleg-nenashev  so according to your approach do we have to do any modifications to the library to make it available for the jenkins UI?

**Comment by MarkEWaite** [comment]
@deshpande-adwait as @oleg-nenashev said:

> we could add a new mode which installs plugins on a running Jenkins instance using REST API or CLI, but I am not sure the tool is a best location for that

The Jenkins command line interface already supports plugin installation.  @darinpope provided a video that shows how to install plugins with the Jenkins command line interface.  It is embedded in the Jenkins documentation at https://www.jenkins.io/doc/book/managing/plugins/#install-with-cli

I've not found many cases where "install plugins without restart" actually provided the results that I wanted.  Yes, the plugins are installed, and yes it does not restart Jenkins, but that does not consistently give me the full functionality of the things that I installed until I've done a restart.

**Comment by deshpande-adwait** [comment]
> @deshpande-adwait as @oleg-nenashev said:
> 
> > we could add a new mode which installs plugins on a running Jenkins instance using REST API or CLI, but I am not sure the tool is a best location for that
> 
> The Jenkins command line interface already supports plugin installation. @darinpope provided a video that shows how to install plugins with the Jenkins command line interface. It is embedded in the Jenkins documentation at https://www.jenkins.io/doc/book/managing/plugins/#install-with-cli
> 
> I've not found many cases where "install plugins without restart" actually provided the results that I wanted. Yes, the plugins are installed, and yes it does not restart Jenkins, but that does not consistently give me the full functionality of the things that I installed until I've done a restart.

Yes, that does make sense. It would be good to have restarts once in a while. And yes- I have seen the video by @darinpope to install plugins via the jenkins-plugin-manager tool; that was helpful indeed!

Maybe this can be closed then! Thanks again!
