### ISSUE TITLE
Please set a custom user agent when downloading files

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/plugin-installation-manager-tool#313]
### Dependencies

n/a

### Feature Request

Please specify a custom user-agent when downloading files from updates.jenkins.io so requests can properly be attributed to this tool.

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by hp77-creator** [comment]
@daniel-beck Do you also suggest including the version in the User-agent information?

**Comment by daniel-beck** [comment]
Could be useful, but would not say it's required if there are reasons not to. Thanks for checking!

**Comment by hp77-creator** [comment]
I am trying to include the version as well using the `.properties` file, facing some errors but I think It might be possible!
