### ISSUE TITLE
GSoC 2021 - Plugin Installation Manager project discussion

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/plugin-installation-manager-tool#320]
On April 13, 7AM UTC, we will host a special session about the Jenkins plugin installation manager project idea. All potential students, mentors and Plugins Installation Manager contributors are welcome to join. The meeting will be recorded and posted in the Plugin Installation Manager repository if relevant..

* Project page: https://www.jenkins.io/projects/gsoc/2021/project-ideas/plugin-installation-manager-tool/
* Calendar link with Zoom link: https://calendar.google.com/event?action=TEMPLATE&tmeid=NDhiMGpoZzdjcDNmN3JlazY4cWl2MWptcmYgNHNzMTJmMG1xcjN0YnAxdDJmZTM2OXNsZjRAZw&tmsrc=4ss12f0mqr3tbp1t2fe369slf4%40group.calendar.google.com

FYI @hp77-creator

**Comment by MarkEWaite** [comment]
Closing issue, since the recording is available at https://www.youtube.com/watch?v=QJcwcLnHjRw
