### ISSUE TITLE
Passing -Dhttp.agent='Chrome/92.0.4515.131' to java jenkins-plugin-manager.jar does not get honored

### ISSUE THREAD

**Issue by hectoralicea** [jenkinsci/plugin-installation-manager-tool#363]
Passing -Dhttp.agent='Chrome/92.0.4515.131' to java jenkins-plugin-manager.jar does not get honored which is required when passing through a corporate proxy.  Our corp proxy requires an agent source such as chrome.

### Version report
2.10.3
Jenkins and plugins versions report:

```
any plugin, does not matter
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
RedHat 7.9
```

### Reproduction steps

Step One in a terminal session run tcpdump as such:
```
sudo tcpdump -i 3 -A -s 10240 'tcp port 8080' | grep -v IP | egrep --line-buffered "..(GET |\.HTTP\/|POST |HEAD )|^[A-Za-z0-9-]+: " |sed -r 's/..(GET |HTTP\/|POST |HEAD )/\n\n\1/g'
```

On another terminal window from the same Linux server run the following on command line as such:
```
java \
  -Dhttp.agent='Chrome/92.0.4515.131' \
  -Dhttp.proxyHost=10.X.X.X \
  -Dhttp.proxyPort=8080 \
  -Dhttps.proxyHost=10.X.X.X \
  -Dhttps.proxyPort=8080 \
  -jar /opt/jenkins-plugin-manager.jar \
     --plugin-file /var/jenkins_home/plugins.txt \
     --verbose
```
where 10.X.X.X is the ip of our corporate proxy and it goes through port 8080.

### Results - from the tcpdump, which is what matters.
```
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens5, link-type EN10MB (Ethernet), capture size 10240 bytes
Host: updates.jenkins.io
User-Agent: JenkinsPluginManager/2.10.3-SNAPSHOT
Cache-Control: no-cache
Pragma: no-cache
X-XSS-Protection: 1
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
Content-Length: 1398
Host: updates.jenkins.io
User-Agent: JenkinsPluginManager/2.10.3-SNAPSHOT
Cache-Control: no-cache
Pragma: no-cache
X-XSS-Protection: 1
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
Content-Length: 1398
^C40 packets captured
40 packets received by filter
0 packets dropped by kernel
```
Expected result:
```
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens5, link-type EN10MB (Ethernet), capture size 10240 bytes
Host: updates.jenkins.io
User-Agent: JenkinsPluginManager/2.10.3-SNAPSHOT Chrome/92.0.4515.131
Cache-Control: no-cache
Pragma: no-cache
X-XSS-Protection: 1
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
Content-Length: 1398
Host: updates.jenkins.io
User-Agent: JenkinsPluginManager/2.10.3-SNAPSHOT
Cache-Control: no-cache
Pragma: no-cache
X-XSS-Protection: 1
Content-Type: text/html; charset=utf-8
Proxy-Connection: close
Connection: close
Content-Length: 1398
^C40 packets captured
40 packets received by filter
0 packets dropped by kernel
```

Actual result:
is what was posted above as result.

 Note:  What is being sent is:

**User-Agent: JenkinsPluginManager/2.10.3-SNAPSHOT**

rather than what should be sent based on the -Dhttp.agent option is

**User-Agent: JenkinsPluginManager/2.10.3-SNAPSHOT Chrome/92.0.4515.131**

**Comment by timja** [comment]
There’s no flag available currently for this.

Doesn’t this proxy behaviour break a lot of software? It’s very common for command line tools to set their own user agent

**Comment by hectoralicea** [comment]
> Doesn’t this proxy behaviour break a lot of software? It’s very common for command line tools to set their own user agent

yes it does.  I'll need to figure out how to pass this down.  This is a terrible problem, that -Dhttp.agent is not being passed down.  It should at least append it.

**Comment by hectoralicea** [comment]
>>> There’s no flag available currently for this.
I tested out a simple fix that works quite well.  Here's the merge request
See: https://github.com/jenkinsci/plugin-installation-manager-tool/pull/364

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/plugin-installation-manager-tool/pull/364

**Comment by hectoralicea** [comment]
@timja when will the new master build release of this component bubbup to being used in the helm chart here:
https://github.com/jenkinsci/helm-charts/blob/604d7eb36345dae37b74bd63a374dc83f9676daf/charts/jenkins/values.yaml#L22

**Comment by timja** [comment]
It needs a PR to https://github.com/jenkinsci/docker, and then weeklys are released every Tuesday, LTS is currently scheduled for 22nd September.

You can build your own image, this is an example config for using your own version:
https://github.com/hmcts/cnp-jenkins-docker/commit/dc6f62f454a5deb20fa2a347c04a773bdfdfba72

(the commit is me removing our override)
