### ISSUE TITLE
Support Proxy Basic Authentication

### ISSUE THREAD

**Issue by andrewm-aero** [jenkinsci/plugin-installation-manager-tool#366]
### Dependencies

N/A

### Feature Request

The original install-plugins.sh, as well as Jenkins itself supports basic authentication for HTTP(s) proxies, however, the README states that something like CNTLM is required to achieve the same functionality. The JVM properties http(s).proxy[User/Password] are in common enough use, as are authenticated corporate proxies, that that they ought to be supported. Deprecating install-plugins.sh without porting this existing functionality would break many setups when install-plugins.sh is eventually removed.

**Comment by oleg-nenashev** [comment]
I am breaking down options in #237 . After it is completed, it should be easier to introduce new options like proxy auth

**Comment by amfleurke** [comment]
I think this issue can be closed. The plugin-installation-manager tool supports proxy via default java options (-Dhttps.proxyHost etc)
See also project readme.md. Works for me.
