### ISSUE TITLE
Unable to capture verbose log output

### ISSUE THREAD

**Issue by jakovistuk** [jenkinsci/plugin-installation-manager-tool#493]
### Jenkins and plugins versions report

Linux/Ubuntu openjdk version "11.0.15" 2022-04-19

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux/Ubuntu openjdk version "11.0.15" 2022-04-19Linux/Ubuntu 

### Reproduction steps

1. Download different versions.  https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.6/jenkins-plugin-manager-2.12.6.jar and  https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.9/jenkins-plugin-manager-2.12.9.jar
2. Create plugin download list, for example:
 plugins:
- artifactId: javax-activation-api
  source:
    version: latest
- artifactId: javax-mail-api
  source:
    version: latest
- artifactId: bouncycastle-api
  source:
    version: latest
- artifactId: instance-identity
  source:
    version: latest
- artifactId: ionicons-api
  source:
    version: latest
- artifactId: cloudbees-folder
  source:
    version: latest

3. Run:
 java -jar jenkins-plugin-manager-2.12.6.jar  --jenkins-version 2.377  --plugin-download-directory plugin-dir  --plugin-file plugins-download.yaml --verbose > log.txt

4. Run:
 java -jar jenkins-plugin-manager-2.12.9.jar  --jenkins-version 2.377  --plugin-download-directory plugin-dir  --plugin-file plugins-download.yaml --verbose > log.txt

jenkins-plugin-manager-2.12.6.jar  from step 3. creates log.txt and   jenkins-plugin-manager-2.12.9.jar from step 4. does not  populate log.txt. 

### Expected Results

log.txt should be populated as in 2.12.6 version.

### Actual Results

creating and population of log.txt works differently in 2.12.7. 2.12.8 and 2.12.9 ( it is empty). In <2.12.6 versions it is ok

**Comment by MarkEWaite** [comment]
As far as I understand it, this is an intentional change that was made in 

* https://github.com/jenkinsci/plugin-installation-manager-tool/pull/448

It is documented in [2.12.7 changelog](https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.7) and in the [README](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/README.md#development)
