### ISSUE TITLE
Failed publish step for latest release

### ISSUE THREAD

**Issue by bendem** [jenkinsci/plugin-installation-manager-tool#525]
https://github.com/jenkinsci/plugin-installation-manager-tool/actions/runs/4121478791

Something broke during the release process, is there anyone able to fix it?

**Comment by timja** [comment]
Thanks for reporting!

**Comment by bendem** [comment]
Perfect! Not sure if you are able to run it again, latest version has not been published so you can't download it from the release assets.

**Comment by timja** [comment]
no I'll do another release and just burn the previous one to make sure this is working

**Comment by timja** [comment]
see https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.11

**Comment by MarkEWaite** [comment]
I downloaded the 2.12.10 release artifact from the [Jenkins artifact repository](https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugin-management/plugin-management-cli/2.12.10/plugin-management-cli-2.12.10.jar), renamed it to match the artifacts for other releases, and uploaded it as an asset for the [2.12.10 release](https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.10).
