### ISSUE TITLE
Deprecated actions need updating

### ISSUE THREAD

**Issue by timja** [jenkinsci/plugin-installation-manager-tool#527]
see https://github.com/jenkinsci/plugin-installation-manager-tool/actions/runs/4125899094

[publish](https://github.com/jenkinsci/plugin-installation-manager-tool/actions/runs/4125899094/jobs/7127075945)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/upload-release-asset@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
[publish](https://github.com/jenkinsci/plugin-installation-manager-tool/actions/runs/4125899094/jobs/7127075945#step:6:12)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/21194782/217581157-9f95ad5f-9102-4158-af28-bb0d59fe1ff6.png">

cc @lemeurherve / @NotMyFault who I think have done quite a few of these if you have any links that would be useful 😄

**Comment by NotMyFault** [comment]
To mitigate the warning by the release uploader, we can use what I did for core: https://github.com/jenkinsci/jenkins/commit/388f86d7cd1e0c36b50e62f974b8fc35f27e1cf3
