### ISSUE TITLE
Move developer instructions to a new contributing guide

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/plugin-installation-manager-tool#529]
### Describe your use-case which is not covered by existing documentation.

Move the instructions at the end of the README to a separate contributing guide, modeled after the guides that are referenced in the ["Improve a Plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/add-a-contributing-guide/)

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

See the tutorial for references of the types of topics to include.  Some suggestions might include:

* Build and test
* Coverage reporting
* ...

**Comment by AmanGupta677** [comment]
I would like to work on this issue can you assign it to me, and also how do I get started.

**Comment by MarkEWaite** [comment]
@AmanGupta677 we don't assign issues to new contributors because we've had poor experiences when they express interest, we assign an issue, then no progress is made.

Your message

> I would like to work on this issue can you assign it to me, and also how do I get started.

is enough to tell others that you're interested in working on this issue.  A pull request to show progress on the issue is the next step.

You get started by moving the contribution related text from the end of the README to a new file, usually named `CONTRIBUTING.md`.  Create a pull request proposing to add that file to the repository.  See the ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/add-a-contributing-guide/) and other tutorials related to it for videos that show how to submit a pull request.

**Comment by AmanGupta677** [comment]
Thanks for your response. I appreciate the guidance on the next step to take and will proceed to submit a pull request to show my progress on the issue.
