### ISSUE TITLE
Release 2.12.12 incomplete (JAR file not published)

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/plugin-installation-manager-tool#577]
Hello there 👋 

The last release [2.12.12](https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.12) does not have a JAR file attachement like previous versions, causing build errors in downstream PR https://github.com/jenkinsci/docker/pull/1667 which relies on downloading the published artefact.

<img width="1260" alt="Capture d’écran 2023-07-11 à 08 28 52" src="https://github.com/jenkinsci/plugin-installation-manager-tool/assets/1522731/d08857eb-87ed-453f-935a-3e294580a0e3">

It comes from an incomplete release: the GitHub action "Publish" triggered by the release/tag  creation failed with the error `Unable to resolve action actions/upload-asset, repository not found`

<img width="970" alt="Capture d’écran 2023-07-11 à 08 27 47" src="https://github.com/jenkinsci/plugin-installation-manager-tool/assets/1522731/d7caba5e-ead2-4f46-bd7c-24fced1ea2b4">

The action [upload-release-asset](https://github.com/actions/upload-release-asset) is archived, which explains why it's failing.

**Comment by dduportal** [comment]
Proposal : I'm gonna open a PR to switch using the `gh` command line inb the publish process, as there are no certified GitHub action (and using a 3rd party is a bit weird for this )

**Comment by dduportal** [comment]
@MarkEWaite @timja I'm not maintainer here, may I ask you to:

- Upload manually the JAR file (with the proper naming) to the current 2.12.12
- Review https://github.com/jenkinsci/plugin-installation-manager-tool/pull/578 so we can test a 2.12.13 release

?

**Comment by timja** [comment]
> Upload manually the JAR file (with the proper naming) to the current 2.12.12

I would rather test while we are in context rather than months later 😄

**Comment by timja** [comment]
Looks like it worked? https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.13

**Comment by dduportal** [comment]
> > Upload manually the JAR file (with the proper naming) to the current 2.12.12
> 
> I would rather test while we are in context rather than months later 😄

I don't mind a new release at all (I also aimed at a new 2.12.13 with my PR, but that let a "broken" release in the GitHub release history while the artifactory history has it.

**Comment by dduportal** [comment]
> Looks like it worked? https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.13

Yep, victory \o/ I'm closing the issue, I let the maintainers judge of if it is worth uploading the 2.12.12 or not :)

Thanks!

**Comment by timja** [comment]
not worth it to me 😄

**Comment by MarkEWaite** [comment]
I would prefer to upload the 2.12.12 artifact for consistency and am happy to be the maintainer that does it.  However, I can't find that artifact on https://repo.jenkins-ci.org .  I also can't find the 2.12.13 artifact on repo.jenkins-ci.org .

I see plugin-management-cli in the https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugin-management/ and but I don't see the jenkins-plugin-manager-x.xx.xx.jar file on repo.

The jenkins-plugin-manager-x.xx.xx.jar Main class has a fully qualified class `io.jenkins.tools.pluginmanager.cli.Main` yet https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/tools/ shows that there is no directory for `pluginmanager` under `io.jenkins.tools`.

Can someone help me with my weak Artifactory search skills?

**Comment by dduportal** [comment]
> I would prefer to upload the 2.12.12 artifact for consistency and am happy to be the maintainer that does it. However, I can't find that artifact on https://repo.jenkins-ci.org . I also can't find the 2.12.13 artifact on repo.jenkins-ci.org .
> 
> I see plugin-management-cli in the https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugin-management/ but I don't see the jenkins-plugin-manager-x.xx.xx.jar file on repo.
> 
> The jenkins-plugin-manager-x.xx.xx.jar Main class has a fully qualified class `io.jenkins.tools.pluginmanager.cli.Main` yet https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/tools/ shows that there is no directory for `pluginmanager` under `io.jenkins.tools`.
> 
> Can someone help me with my weak Artifactory search skills?

If you look at the release process workflow file (https://github.com/jenkinsci/plugin-installation-manager-tool/blob/c795ccd05c0c48b9dc624eb82511331acbe12fff/.github/workflows/publish-release-artifact.yml) you'll see on the [line 32](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/c795ccd05c0c48b9dc624eb82511331acbe12fff/.github/workflows/publish-release-artifact.yml#L32) that it downloads the jar file from JFrog.

As per https://github.com/jenkinsci/plugin-installation-manager-tool/blob/c795ccd05c0c48b9dc624eb82511331acbe12fff/.github/workflows/publish-release-artifact.yml#L27, it's  the `plugin-management-cli` artefact.

E.g. from https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugin-management/plugin-management-cli/2.12.12/ for this release.

@MarkEWaite is that ok for you?

**Comment by MarkEWaite** [comment]
> If you look at the release process workflow file (https://github.com/jenkinsci/plugin-installation-manager-tool/blob/c795ccd05c0c48b9dc624eb82511331acbe12fff/.github/workflows/publish-release-artifact.yml) you'll see on the [line 32](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/c795ccd05c0c48b9dc624eb82511331acbe12fff/.github/workflows/publish-release-artifact.yml#L32) that it downloads the jar file from JFrog.

As far as I can tell, the jar file that it downloads (https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugin-management/plugin-management-cli/2.12.12/plugin-management-cli-2.12.12.jar) is then packaged with an additional Java class () and that is used to create the delivered jar file,  I am unable to find an archive of the delivered jar file

**Comment by dduportal** [comment]
> > If you look at the release process workflow file (https://github.com/jenkinsci/plugin-installation-manager-tool/blob/c795ccd05c0c48b9dc624eb82511331acbe12fff/.github/workflows/publish-release-artifact.yml) you'll see on the [line 32](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/c795ccd05c0c48b9dc624eb82511331acbe12fff/.github/workflows/publish-release-artifact.yml#L32) that it downloads the jar file from JFrog.
> 
> As far as I can tell, the jar file that it downloads (https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugin-management/plugin-management-cli/2.12.12/plugin-management-cli-2.12.12.jar) is then packaged with an additional Java class and that is used to create the delivered jar file, I am unable to find an archive of the delivered jar file

The release process "only" uploads (as attachement to the freshly published GitHub release) the file downloaded with wget: https://github.com/jenkinsci/plugin-installation-manager-tool/blob/c795ccd05c0c48b9dc624eb82511331acbe12fff/.github/workflows/publish-release-artifact.yml#L38

**Comment by MarkEWaite** [comment]
Thanks for the explanation.  Now I understand.  The plugin-management-cli-2.12.12.jar downloaded from repo is renamed to jenkins-plugin-manager-2.12.12.jar and uploaded to GitHub.
