### ISSUE TITLE
Sample command in README.md misses download directory option

### ISSUE THREAD

**Issue by nelsonq** [jenkinsci/plugin-installation-manager-tool#607]
### Describe your use-case which is not covered by existing documentation.

The snippet is 
```
java -jar jenkins-plugin-manager-*.jar --war /your/path/to/jenkins.war --plugin-file /your/path/to/plugins.txt --plugins delivery-pipeline-plugin:1.3.2 deployit-plugin
```

It misses download directory option. I am getting follow error
```
Unable to create plugin directory: '/usr/share/jenkins/ref/plugins', supply a directory with -d <your-directory>
```

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

[In this https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/README.md](https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/README.md#getting-started)

**Comment by timja** [comment]
would you like to send a pull request to fix it?

**Comment by nelsonq** [comment]
For sure. I will raise a PR for it.
