### ISSUE TITLE
Trying to download a plugin version that has not yet been published but is on github

### ISSUE THREAD

**Issue by ninjonxb** [jenkinsci/plugin-installation-manager-tool#647]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Using docker.io/jenkins/jenkins:jdk11@sha256:338d6c495f56720b07cc1f8d6b5c8a29127c4496c35c5fc5f53461731d7b491e running on Amazon Linux 2
Being built within a jenkins job

### Reproduction steps

The steps to reproduce this will likely change since by the time this is resolved this exact instance of the problem will be resolved.
In our plugin.txt we have the following:
```
bitbucket-scm-trait-commit-skip
bitbucket-approval-filter
blueocean-bitbucket-pipeline
```

Which share a dependency of
`cloudbees-bitbucket-branch-source`

Run the tool with this file

### Expected Results

For it to download the latest version of the plguin as shown on jenkins plugins

### Actual Results

It is downloading a version of the plugin that is live on github but is not on Jenkins Plugins yet.

```
#7 7.111 Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/cloudbees-bitbucket-branch-source/873.v0ed259216f8d/cloudbees-bitbucket-branch-source.hpi, or download plugin cloudbees-bitbucket-branch-source to file: status code: 404, reason phrase: Not Found
#7 7.112 Tried downloading cloudbees-bitbucket-branch-source from https://archives.jenkins.io/plugins/cloudbees-bitbucket-branch-source/873.v0ed259216f8d/cloudbees-bitbucket-branch-source.hpi (attempt 1 of 3)
#7 7.252 Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/cloudbees-bitbucket-branch-source/873.v0ed259216f8d/cloudbees-bitbucket-branch-source.hpi, or download plugin cloudbees-bitbucket-branch-source to file: status code: 404, reason phrase: Not Found
#7 7.253 Tried downloading cloudbees-bitbucket-branch-source from https://archives.jenkins.io/plugins/cloudbees-bitbucket-branch-source/873.v0ed259216f8d/cloudbees-bitbucket-branch-source.hpi (attempt 2 of 3)
#7 7.388 Tried downloading cloudbees-bitbucket-branch-source from https://archives.jenkins.io/plugins/cloudbees-bitbucket-branch-source/873.v0ed259216f8d/cloudbees-bitbucket-branch-source.hpi (attempt 3 of 3)
```

On GitHub the release `873.v0ed259216f8d` has been released but on on Jenkins Plugins:
https://plugins.jenkins.io/cloudbees-bitbucket-branch-source/releases/

`872.vb_8fa_89198661` is the most recent release that can be downloaded

I have also confirmed that if I go into jenkins and attempt to manually update this Plugin, it also pulls the correct version `872.vb_8fa_89198661` not the version that has not been published yet.

![Screenshot 2024-02-13 at 10 01 20 AM](https://github.com/jenkinsci/plugin-installation-manager-tool/assets/3216410/04e95fcd-10da-4126-aa9b-9ff908b68964)
![Screenshot 2024-02-13 at 10 01 45 AM](https://github.com/jenkinsci/plugin-installation-manager-tool/assets/3216410/0560fdf2-a5fb-450c-a292-98b15e5208c6)
![Screenshot 2024-02-13 at 10 01 53 AM](https://github.com/jenkinsci/plugin-installation-manager-tool/assets/3216410/cec62d09-3754-4b98-9e93-db262f4cadd8)

### Anything else?

I imagine that if I wait a bit this will resolve itself once this version has been properly published and is a case of bad timing. But it seems like the plugin is looking up what version to install in a different way than the GUI for Jenkins does.

I should note that the version of Jenkins GUI that I am testing this on is different than the Container mentioned above since it is from an earlier deployment just incase something else changed. That version is 2.431

**Comment by ninjonxb** [comment]
Since I have been refreshing multiple times today waiting for the version it is trying to download to be available, I noticed that when I refreshed the version I wanted would briefly show and then would be removed by javascript.

I don't know enough about the jenkins plugins website to know why this could be the case, but there is still some reason that the Jenkins GUI seems to be handling this but the plugin tool does not.

**Comment by lemeurherve** [comment]
Could you try again after clicking on the "Update information" button please?

I see the last 873 version here:

<img width="403" alt="image" src="https://github.com/jenkinsci/plugin-installation-manager-tool/assets/91831478/1bf299cb-f1c6-4f8e-b592-3f68b0d0d17e">

**Comment by lemeurherve** [comment]
@timja @NotMyFault could one of you migrate this issue to the helpdesk please?

**Comment by ninjonxb** [comment]
So 873 is now published, so the initial problem itself is resolved.

However there is still the root issue that it was trying to download a version that it shouldn't be and has different behavior than the Jenkins GUI in that regard.

That should likely be fixed unless this is expected behavior, but I can't imagine it is.

**Comment by NotMyFault** [comment]
> @timja @NotMyFault could one of you migrate this issue to the helpdesk please?

Transferring issues across organizations isn't a thing, unfortunately :(

**Comment by lemeurherve** [comment]
@ninjonxb could you open an issue at https://github.com/jenkins-infra/helpdesk/issues if you want to continue on the subject please?
