### ISSUE TITLE
--latest ignores whether the plugin is actually available or not

### ISSUE THREAD

**Issue by EcHoOfInSaNiTy** [jenkinsci/plugin-installation-manager-tool#87]
If I want to resolve the latest dependencies for my Jenkins plugins I often run into a scenario where a plugin is in the process of being bumped to a newer version (by the maintainer), and this is reflected on the jenkins update center as a new directory, however the actual jpi hasn't been uploaded yet so it fails to download. This is troublesome as if I test that the plugins are available in a test environment before rolling to production, there could be a plugin version bump in progress that causes a failure in the time between testing in the test environment and moving it to production.

Perhaps a `--latest-available` flag that checks if there is a jpi available and if not rolls to the previous release of a plugin would avoid this? To play devils advocate, I can't see why someone would want this behaviour using `--latest` in the first place.

**Comment by timja** [comment]
Not sure if it's something we want to solve here, it's more a jenkins infrastructure problem, that it reports the update before it's actually available on all mirrors yet, and you can be sent to a mirror that doesn't have it 😢

**Comment by EcHoOfInSaNiTy** [comment]
I agree that it definitely feels like more of a Jenkins Infrastructure problem, however it does in a way undermine this tool (which is great btw).

I believe the infrastructure in question is here: https://github.com/jenkins-infra/update-center2 however it looks like I'm unable to open an issue :cry:

**Comment by timja** [comment]
it uses jira, https://issues.jenkins-ci.org/ (in the infra project)

There's two ongoing workstreams atm that may mitigate or fix it,

1. swap from mirrorbrain to mirrorbit, with the added benefit that it will support ssl as well
2. use fastly as a CDN and don't do any mirroring at all (waiting for stuff to be signed I think)

@olblak may be able to comment more

**Comment by olblak** [comment]
Indeed it's more an infrastructure issue,as @timja mentioned it, I am currently testing a tool called mirrobits  which only provide a file from a mirror if the md5sum match the one from mirrobits otherwise it falls back to a specific mirror. So you always get the same latest file

**Comment by EcHoOfInSaNiTy** [comment]
> Indeed it's more an infrastructure issue,as @timja mentioned it, I am currently testing a tool called mirrobits which only provide a file from a mirror if the md5sum match the one from mirrobits otherwise it falls back to a specific mirror. So you always get the same latest file

This sounds great! Is there an ETA on this? Or a jira issue I can follow?

**Comment by timja** [comment]
Not sure about jira, this is the PR: https://github.com/jenkins-infra/charts/pull/122

Merging of it won’t mean it’s live but it would mean it’s close

**Comment by EcHoOfInSaNiTy** [comment]
I see this was merged, @timja would this resolve this issue?

**Comment by timja** [comment]
> I see this was merged, @timja would this resolve this issue?

not yet, olblak sent an email about it yesterday:
https://groups.google.com/forum/#!topic/jenkins-infra/R7QqpgoSkbI

**Comment by EcHoOfInSaNiTy** [comment]
@timja would your recommendation be to pin plugin versions in the YAML file until this is resolved to improve reliability?

**Comment by timja** [comment]
> @timja would your recommendation be to pin plugin versions in the YAML file until this is resolved to improve reliability?

Yes

**Comment by EcHoOfInSaNiTy** [comment]
> > @timja would your recommendation be to pin plugin versions in the YAML file until this is resolved to improve reliability?
> 
> Yes

I've opened up a PR to update the README [here](https://github.com/jenkinsci/plugin-installation-manager-tool/issues/87) as I think this is valuable information for anyone looking to use this.

**Comment by EcHoOfInSaNiTy** [comment]
Would love to contribute to the project also! This tool has really set a standard for Jenkins plugins IMO.

**Comment by timja** [comment]
> Would love to contribute to the project also! This tool has really set a standard for Jenkins plugins IMO.

All contributions welcomed ❤️ 

I'm not actively developing here but can guide contributions and review / merge PRs

**Comment by EcHoOfInSaNiTy** [comment]
@timja given the update here https://github.com/jenkins-infra/charts/pull/122 it sounds like this won't be fixed for a bit.

How difficult would it be to add an option to skip failed downloads? I noticed you opened an issue to have `--latest` the default, I feel that this will increase the chances of the issue I reported happening to users who desire `--latest`. WDYT?

**Comment by timja** [comment]
Fixed in https://issues.jenkins-ci.org/browse/INFRA-160
