### ISSUE TITLE
Ability to update plugins file to latest version

### ISSUE THREAD

**Issue by nre-ableton** [jenkinsci/plugin-installation-manager-tool#88]
It would be great to have the ability to update the `plugins.yaml` file to the latest version of all plugins.

The way that I currently do that is within an Ansible playbook that does the following:

1. Make a new copy of `plugins.yaml` on the Jenkins master
2. Remove all `version:` lines from that file
3. Run `java -jar jenkins-plugin-manager-{{ jenkins_pimt_version }}.jar -w {{ jenkins_war }} -f /tmp/plugins.yaml -d {{ jenkins_home }}/plugins --available-updates --latest`
4. Run `java -jar {{ jenkins_pimt_location }}/jenkins-plugin-manager-{{ jenkins_pimt_version }}.jar -w {{ jenkins_war }} -f /tmp/plugins.yaml -d {{ jenkins_home }}/plugins --no-download --list > /tmp/plugin-versions.txt`
5. Copy `/tmp/plugin-versions.txt` to the control machine
6. Run a Python script which processes the output of `/tmp/plugin-versions.txt` and generates `plugins.yaml` as output

This is quite a bit of work, and it's also error prone. It also means that our `plugins.yaml` has to track _everything_, making it act like a lockfile. This also means that removing plugins (which does happen occasionally) is cumbersome, since that plugin's dependencies are still tracked in `plugins.yaml` and need to be removed manually.

It would be nice if plugin-installation-manager-tool had an option to generate an updated version of `plugins.yaml` based on the current version and whatever plugin updates were available. Truthfully, our team doesn't much care about plugin dependency versions or transitive dependency versions -- we only care about the versions of the plugins we directly want to install. But that means when we run plugin-installation-manager-tool, I would like two things to happen:

1. The plugins installed from `plugins.yaml` are always installed at the exact version specified
2. Everything else (all dependencies, transitive dependencies, etc) are updated if necessary

This issue was created as a result of the discussion in https://github.com/jenkinsci/plugin-installation-manager-tool/issues/85.

**Comment by oleg-nenashev** [comment]
It is somewhat related to #99

**Comment by jetersen** [comment]
Hopefully #114 should make it easier to output a yaml file :)
