### ISSUE TITLE
Make --latest the default

### ISSUE THREAD

**Issue by timja** [jenkinsci/plugin-installation-manager-tool#90]
`--latest` only affects dependency resolution

It's not great to request a plugin and to see it install 5 other dependencies and see that they now need updating, which leads to either having to specify every plugin, or learning about the `--latest` flag.

Proposal:

Changing the flag to take an argument:
```
--latest=true
--latest=false
```

And have it default to true

**Comment by martinda** [comment]
Would this break backward compatibility? (both answers are fine by the way).

**Comment by timja** [comment]
> Would this break backward compatibility? (both answers are fine by the way).

it's a behavioural change, but not sure if you would class it as breaking. Passing --latest would be the same as --latest=true, which would be the new default

**Comment by martinda** [comment]
So it does not change the behavior for users already calling with `--latest`. Would this change things for users not calling with --latest?

**Comment by timja** [comment]
> So it does not change the behavior for users already calling with `--latest`. Would this change things for users not calling with --latest?

Yes, they would get the latest dependencies available and not the ones declared in the plugins pom file

**Comment by martinda** [comment]
So the behavior would change for users that don't use `--latest`.

**Comment by oleg-nenashev** [comment]
I added it to the 2.0 scope. Installing latest by default is how the existing Jenkins core logic operates, so I would follow the same behavior
