### ISSUE TITLE
running behind proxy

### ISSUE THREAD

**Issue by shurikg** [jenkinsci/plugin-installation-manager-tool#95]
What I need to define in order to run behind proxy?

I tried to define the env http/s_proxy but without success

**Comment by timja** [comment]
https://stackoverflow.com/a/120802/4951015

https://stackoverflow.com/a/11527488/4951015

**Comment by shurikg** [comment]
with the above -D the command success to download the update json file, but still failed on download the plugins itself

command that I run:

 java -Dhttps.proxyHost=XXXX -Dhttps.proxyPort=8080 -jar jenkins-plugin-manager-1.0.2.jar --war ./jenkins.war --plugins delivery-pipeline-plugin:1.3.2   -d ./a  --verbose

the error is:

Downloading plugin cloudbees-folder-plugin from url: https://updates.jenkins.io/download/plugins/cloudbees-folder-plugin/6.1.2/cloudbees-folder-plugin.hpi
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/workflow-basic-steps/2.6/workflow-basic-steps.hpi, or download plugin workflow-basic-steps to file
First download attempt of workflow-basic-steps unsuccessful, reattempting

Downloading plugin workflow-basic-steps-plugin from url: https://updates.jenkins.io/download/plugins/workflow-basic-steps-plugin/2.6/workflow-basic-steps-plugin.hpi
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/pipeline-input-step-plugin/2.0/pipeline-input-step-plugin.hpi, or download plugin pipeline-input-step-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jquery-plugin/1.7.2-1/jquery-plugin.hpi, or download plugin jquery-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/delivery-pipeline-plugin-plugin/1.3.2/delivery-pipeline-plugin-plugin.hpi, or download plugin delivery-pipeline-plugin-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/script-security-plugin/1.39/script-security-plugin.hpi, or download plugin script-security-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/token-macro-plugin/1.12.1/token-macro-plugin.hpi, or download plugin token-macro-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/workflow-cps-plugin/2.43/workflow-cps-plugin.hpi, or download plugin workflow-cps-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/workflow-step-api-plugin/2.13/workflow-step-api-plugin.hpi, or download plugin workflow-step-api-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/workflow-scm-step-plugin/2.4/workflow-scm-step-plugin.hpi, or download plugin workflow-scm-step-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/junit-plugin/1.20/junit-plugin.hpi, or download plugin junit-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/jquery-detached-plugin/1.2.1/jquery-detached-plugin.hpi, or download plugin jquery-detached-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/workflow-multibranch-plugin/2.17/workflow-multibranch-plugin.hpi, or download plugin workflow-multibranch-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/pipeline-stage-view-plugin/2.5/pipeline-stage-view-plugin.hpi, or download plugin pipeline-stage-view-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/scm-api-plugin/2.2.6/scm-api-plugin.hpi, or download plugin scm-api-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/momentjs-plugin/1.1/momentjs-plugin.hpi, or download plugin momentjs-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/pipeline-graph-analysis-plugin/1.1/pipeline-graph-analysis-plugin.hpi, or download plugin pipeline-graph-analysis-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/ace-editor-plugin/1.0.1/ace-editor-plugin.hpi, or download plugin ace-editor-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/workflow-job-plugin/2.17/workflow-job-plugin.hpi, or download plugin workflow-job-plugin to file
Unable to resolve plugin URL https://updates.jenkins.io/download/plugins/workflow-support-plugin/2.17/workflow-support-plugin.hpi, or download plugin workflow-support-plugin to file
io.jenkins.tools.pluginmanager.impl.DownloadPluginException: Unable to download pipeline-input-step-plugin
        at io.jenkins.tools.pluginmanager.impl.PluginManager.lambda$null$4(PluginManager.java:427)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by timja** [comment]
you only set the https proxy, you need to set http and https

**Comment by shurikg** [comment]
yes, you are right, now is better :)

Thanks a lot

**Comment by jansohn** [comment]
Additionally supporting environment variables (HTTP_PROXY/HTTPS_PROXY/NO_PROXY) would still be nice IMHO...

**Comment by timja** [comment]
try `-Djava.net.useSystemProxies=true`
https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html

**Comment by jansohn** [comment]
> 
> 
> try `-Djava.net.useSystemProxies=true`
> https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html

just tried it, doesn't work...

    jenkins@9b8b817b3adc:/$ env | grep -i proxy
    no_proxy=localhost,127.0.0.1,mycompany.com
    https_proxy=http://ep.threatpulse.net:80
    http_proxy=http://ep.threatpulse.net:80
    jenkins@9b8b817b3adc:/$ java -Djava.net.useSystemProxies=true -jar /usr/lib/jenkins-plugin-manager.jar -p $(< /usr/share/jenkins/ref/plugins.txt.override)
    Error getting update center json

**Comment by rafaelpirolla** [comment]
For future reference sometimes the proxy might dislike the way the software downloads the plugins. In a dockerfile  i had to make a loop instead of passing the file for the manager.

```
RUN sh -c export JAVA_TOOL_OPTIONS="-Dhttps.proxyHost=${PROXY_HOST} -Dhttps.proxyPort=${PROXY_PORT} -Dhttp.proxyHost=${PROXY_HOST} -Dhttp.proxyPort=${PROXY_PORT}" && \
cat /usr/share/jenkins/plugins.txt | while read line; \
do /bin/jenkins-plugin-cli --war "/usr/share/jenkins/jenkins.war" --plugins "$line"; done
```
