### ISSUE TITLE
Optional dependencies aren't handled correctly

### ISSUE THREAD

**Issue by grv87** [jenkinsci/plugin-installation-manager-tool#96]
I just installed some plugins with this tool (without using `--latest`) and got this error:

```
Jenkins Git plugin (3.9.3)
Update required: Jenkins Parameterized Trigger plugin (2.21) to be updated to 2.33 or higher
Jenkins promoted builds plugin (3.5)
Update required: Config File Provider Plugin (2.16.4) to be updated to 2.18 or higher
```

These dependencies are optional.
Looks like Jenkins Parameterized Trigger plugin (2.21) and Config File Provider Plugin (2.16.4) were required by some other plugins.
And Jenkins expects optional dependency not to be installed at all or to have specified version.

Jenkins version 2.222.3.

**Comment by oleg-nenashev** [comment]
I confirm this defect. Currently the tool does not verify optional dependencies. Possible resolutions are to actually add this logic or to use `latest` for implicit dependencies like suggested by @timja in https://github.com/jenkinsci/plugin-installation-manager-tool/issues/90

An obvious workaround would be to hardcode a desired version in the plugin list

**Comment by timja** [comment]
Closing as fixed by https://github.com/jenkinsci/plugin-installation-manager-tool/issues/90
