### ISSUE TITLE
Add an option to generate a new updates file in `available-updates`

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/plugin-installation-manager-tool#99]
Currently the tool generates the following output:

```
Available updates:
blueocean-config (1.14.0) has an available update: 1.23.2
jdk-tool (1.2) has an available update: 1.4
github-branch-source (2.3.2) has an available update: 2.7.1
blueocean-pipeline-api-impl (1.14.0) has an available update: 1.23.2
workflow-multibranch (2.20) has an available update: 2.21
docker-workflow (1.14) has an available update: 1.23
maven-plugin (2.17) has an available update: 3.6
pipeline-stage-tags-metadata (1.3.2) has an available update: 1.6.0
git-client (2.7.3) has an available update: 3.2.1
scm-api (2.2.8) has an available update: 2.6.3
email-ext (2.65) has an available update: 2.69
github (1.26.0) has an available update: 1.30.0
```

It would be great if the tool had support for generating a plugins.txt or YAML with the resulting list of plugins after the update. It would save a lot of time on managing dependencies when using the tool.

**Comment by timja** [comment]
Bonus points for:

* pinning versions of a plugin (so it doesn't try update it)
* preserving comments in the existing file (they would normally be there to say why a plugin is needed or why it can't be upgraded currently)
